stages:
  - build
  - deploy

variables:
  API_IMAGE: "$CI_REGISTRY_IMAGE:api"
  WORKER_IMAGE: "$CI_REGISTRY_IMAGE:worker"

build-api:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  tags:
    - shell
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $API_IMAGE --target api -f Dockerfile .
    - docker push $API_IMAGE

build-worker:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  tags:
    - shell
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $WORKER_IMAGE --target worker -f Dockerfile.worker .
    - docker push $WORKER_IMAGE

deploy-to-minikube:
  stage: deploy
  tags:
    - shell
  script:
    - $env:KUBECONFIG = "C:/Users/seang/.kube/config"
    - kubectl apply -f k8s/api-deployment.yaml
    - kubectl apply -f k8s/worker-deployment.yaml
