stages:
  - build
  - deploy

variables:
  API_IMAGE: registry.gitlab.com/seang38077-group/leetcode-rating:api
  WORKER_IMAGE: registry.gitlab.com/seang38077-group/leetcode-rating:worker

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build-api:
  stage: build
  script:
    - docker build -t $API_IMAGE --target api -f Dockerfile .
    - docker push $API_IMAGE

build-worker:
  stage: build
  script:
    - docker build -t $WORKER_IMAGE --target worker -f Dockerfile.worker .
    - docker push $WORKER_IMAGE

deploy-to-gke:
  stage: deploy
  image: google/cloud-sdk:latest
  only:
    - main
  before_script:
    - echo "$GCP_SERVICE_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project leetcoderating
    - gcloud config set compute/zone asia-east1-a
    - gcloud container clusters get-credentials leetcode-cluster
  script:
    - kubectl apply -f k8s/api-deployment.yaml
    - kubectl apply -f k8s/worker-deployment.yaml
