stages:
  - build
  - deploy

variables:
  PROJECT_NAME: "leetcode-rating"
  API_IMAGE: "registry.gitlab.com/seang38077-group/leetcode-rating:api"
  WORKER_IMAGE: "registry.gitlab.com/seang38077-group/leetcode-rating:worker"

api-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $API_IMAGE --target api .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $API_IMAGE

worker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $WORKER_IMAGE --target worker .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $WORKER_IMAGE

.deploy:
  image: google/cloud-sdk:latest
  stage: deploy
  before_script:
    - echo "$GCP_SERVICE_KEY" | base64 -d > ${CI_PROJECT_DIR}/gcloud-key.json
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcloud-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud config set compute/zone $GCP_COMPUTE_ZONE
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME
  script:
    - kubectl apply -f k8s/api-deployment.yaml
    - kubectl apply -f k8s/api-service.yaml
    - kubectl apply -f k8s/worker-deployment.yaml
