stages:
  - build
  - deploy

build-api:
  stage: build
  tags:
    - shell
  script:
    - docker build -t leetcoderating-api:latest -f Dockerfile .

build-worker:
  stage: build
  tags:
    - shell
  script:
    - docker build -t leetcoderating-worker:latest -f Dockerfile.worker .

deploy-api:
  stage: deploy
  tags:
    - shell
  script:
    - kubectl apply -f api-deployment.yaml

deploy-worker:
  stage: deploy
  tags:
    - shell
  script:
    - kubectl apply -f worker-deployment.yaml
    
