image: golang:1.21

services:
  - name: redis:7
  - name: postgres:15
    alias: postgres
  - name: rabbitmq:3-management
    alias: rabbitmq

variables:
  POSTGRES_DB: leetcode
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123
  DATABASE_URL: postgres://postgres:123@postgres:5432/leetcode?sslmode=disable
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

stages:
  - build
  - test

before_script:
  - go mod tidy

build:
  stage: build
  script:
    - mkdir -p bin/
    - go build -o bin/api main.go
    - go build -o bin/worker worker/worker.go
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

test:
  stage: test
  script:
    - echo "✅ 若有測試，請加上 go test ./...，目前僅確保能成功 build."
