# --- 建置階段 ---
FROM golang:1.23.9 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o worker ./worker/worker.go

# --- 執行階段 ---
FROM alpine:latest AS runtime

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/worker .

CMD ["./worker"]
