# --- 建置階段 ---
FROM golang:1.23.9 AS worker

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o worker ./worker/worker.go

# --- 執行階段 ---
FROM alpine:latest

WORKDIR /app

COPY --from=worker /app/worker .


CMD ["./worker"]
