apiVersion: apps/v1
kind: Deployment
metadata:
  name: leetcode-api
  labels:
    app: leetcode-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leetcode-api
  template:
    metadata:
      labels:
        app: leetcode-api
    spec:
      containers:
        - name: api
          image: registry.gitlab.com/seang38077-group/leetcode-rating:api
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis.default.svc.cluster.local:6379"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/"
            - name: DATABASE_URL
              value: "postgres://user:password@postgres.default.svc.cluster.local:5432/leetcode?sslmode=disable"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
