apiVersion: apps/v1
kind: Deployment
metadata:
  name: leetcoderating-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leetcoderating-worker
  template:
    metadata:
      labels:
        app: leetcoderating-worker
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: worker
          image: "registry.gitlab.com/seang38077-group/leetcoderating/leetcoderating-worker:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: leetcoderating-env
