apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      hostNetwork: true
      containers:
        - name: worker
          image: leetcoderating-worker:latest
          env:
            - name: REDIS_URL
              value: "localhost:6379"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@localhost:5672/"
            - name: DATABASE_URL
              value: "postgres://postgres:123@localhost:5432/leetcode?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
